spring.application.name=sb-ecom

project.image=src/main/resources/images



#H2 Configuration
# http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Debugging Properties
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

